#-------------------------------------------------------------------------------
#---GENERAL---------------------------------------------------------------------
#-------------------------------------------------------------------------------

#---APPLICATION SETTINGS--------------------------------------------------------
flowSolver                        = true
gridGenerator                     = false
restartFile                       = false
initRestart                       = false

#---FLOW VARIABLES--------------------------------------------------------------
referenceLength                   = 1.0  # Cylinder diameter
Ma                                = 0.1
Re                                = 200

#---ROTATIONAL FORCING ON CYLINDER----------------------------------------------
lbNoRotationalObjects             = 1
lbBndCndIdx                       = [4]
lbJetCenter                       = [0.0,0.0]       # Center of cylinder for each individually
lbJetRadius                       = [0.5]           # Radius of cylinder
lbRotationAxis                    = [0.0, 0.0]      # rotation axis of each rotational object
lbControlActions                  = [0.0]           # angular velocity in rad

#---I/O-------------------------------------------------------------------------
outputDir.default                 = "out_lb/"
gridInputFileName                 = "grid.Netcdf"
gridOutputFileName                = "grid.Netcdf"
outputInitialCondition            = true #false

#---BALANCING & WEIGHTING-------------------------------------------------------
partitionCellOffspringThreshold   = 200000

#---NUMERICAL PROPERTIES--------------------------------------------------------
nDim                              = 2
noSolvers                         = 2
multiSolverGrid                   = true

executionRecipe                   = "RECIPE_BASE"
solvertype.default                = "MAIA_UNIFIED"

#---SOLUTION PROPERTIES---------------------------------------------------------
restartTimeStep                   = 0
timeSteps                         = 50000
solutionInterval                  = 100000
restartInterval                   = 50000
residualInterval                  = 64000000  # Here, means never

#---GRID PROPERTIES-------------------------------------------------------------
maxNoCells                        = 2000000
scratchSize                       = 10.0

reductionFactor                   = 1.28            # initial cell length is multiplied with this factor

maxRfnmntLvl                      = 10
domainLength                      = 40.0 

#-------------------------------------------------------------------------------
#---LBM-------------------------------------------------------------------------
#-------------------------------------------------------------------------------

#---I/O-------------------------------------------------------------------------
outputDir.0                       = "out_lb/"
geometryInputFileName.0           = "geometry.toml"
useNonSpecifiedRestartFile        = true

#---NUMERICAL PROPERTIES--------------------------------------------------------
solvertype.0                      = "MAIA_LATTICE_BOLTZMANN"
solverMethod                      = "MAIA_LATTICE_BGKC"
noDistributions                   = 9

densityFluctuations               = false
interfaceMethod                   = "FILIPPOVA"
multiBCTreatment                  = "I-W-P"

inOutTest                         = "perpOp"
interpolationDistMethod           = "STD"  # analytic wall distance calculation
gridCutTest                       = "SAT"
interfaceCellSize                 = 10.0 # ratio of number interface cells to overall cells

#---FLOW INITIALIZATION---------------------------------------------------------
#initMethod                        = "LB_LAMINAR_INIT_PX"
initMethod                        = "LB_LAMINAR_CYLINDER_INIT"

initVelocityMethod                = "read"
bndNormalMethod                   = "read"
initialVelocityVectors            = [
                                      1.0, 0.0, # negX
                                      1.0, 0.0, # posX
                                      1.0, 0.0, # negY
                                      1.0, 0.0  # posY
                                    ]
bndNormalVectors                  = [ 
                                      -1.0, 0.0, # negX
                                      1.0, 0.0,  # posX
                                      0.0,-1.0,  # negY
                                      0.0, 1.0   # posY
                                    ]

# ramp viscosity for reasons of stability
tanhInit                          = false   # switch for asymptotic increase of Re
initRe                            = 100.0   # initial Re
initStartTime                     = 0       # global time at which the increase starts (in iterations)
initTime                          = 2000    # time span for asymptotic increase (>99% of final value) (in iterations)

#---GRID PROPERTIES-------------------------------------------------------------
noHaloLayers.0                    = 2

#---SRC TERMS-------------------------------------------------------------------
lbSrcTerms                         = ["LB_SPONGE_EQCONST"]

#---sponge
spongeLayerThickness               = 10.0 # thickness in STL units (0 means off)
spongeThicknessFactor              = [ 0.2,1.0, 0.2,0.2 ] # thickness factor per direction [negX, posX, negY, posY, negZ, posZ]
spongeSigma                        = 0.2 # trg sigma at bndry
spongeBeta                         = 2.0 # exponent of sigma function
spongeTrgRho                       = 1.0
spongeTrgU                         = [ 1.0, 0.0, 0.0 ] # relative to Ma

#---FORCE LOG-------------------------------------------------------------------
calculateWallForces               = false
forceFileName                     = "force.log"
calculateWallForcesInterval       = 1

#-------------------------------------------------------------------------------
#---POST------------------------------------------------------------------------
#-------------------------------------------------------------------------------

#---I/O-------------------------------------------------------------------------
geometryInputFileName.1           = "geometry.toml"
solutionOffset.1                  = 100000000000000000 # Here, never !

#---NUMERICAL PROPERTIES--------------------------------------------------------
solvertype.1                      = "MAIA_POST_DATA"
postProcessing                    = false
noPostProcessing                  = 1
postProcessingSolverIds           = [0]
postProcessingType_0              = "POSTPROCESSING_LB"
postProcessingOps_0               = ["PP_PROBE_POINT_IN"]

#--point sampling
pp_probePath                      = "probe/"
pp_probeCoordinates               = [ -1.0, 0.0]
pp_probeDerivatives               = true

#---GRID PROPERTIES-------------------------------------------------------------
noHaloLayers.1                    = 1
